# Generated by Django 4.0.1 on 2022-03-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('message', models.TextField(default='')),
            ],
            options={
                'db_table': 'contact',
            },
        ),
    ]
