# Generated by Django 4.0.1 on 2022-03-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evotingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voterid', models.CharField(max_length=5)),
                ('issuedate', models.CharField(max_length=10)),
                ('vname', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('vidname', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'regdetails',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voterid', models.CharField(max_length=5)),
                ('dob', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
